version: '3'

services:

  backend:
    build: ./backend
    tty: true
    stdin_open: true
    volumes:
      - ./backend/code:/code

  postgres:
    image: postgres:9.4
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=archipelag
      - POSTGRES_USER=archipelag
      - POSTGRES_DB=archipelag
      - PGPASSWORD=archipelag

volumes:
  postgres-data:
